[package]
name = "advent_of_code2025"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
once_cell = "1.21.3"
reqwest = "0.12.26"
tokio = { version = "1.48.0", features = ["full"] }

